name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyyaml
  - hydra-core=1.3.2
  - pip

  - pip:
      - cmake
      - mlflow
      - wandb
      - numpy<2.0
      - opencv-python==4.10.0.84
