name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pip=23.3.1
  - requests=2.24.0
  - scikit-learn=1.3.2
  - pandas=2.1.3
  - wandb
  - pip:
      - mlflow
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
